data:
  image_dir: "/home/scratch.p3/yuw/datasets/kitti_debug/debug/images"
  ann_path: "/home/scratch.p3/yuw/datasets/kitti_out/mal.json"
  batch_size: 2
  output_image_width: 1000
  output_image_height: 300
  output_dataset: "/home/scratch.p3/yuw/datasets/coco_out/"
spatial_aug:
  rotation:
    angle: [0, 10, 30]
gpu_ids: [0]
num_gpus: 1
