results_dir: ??
data:
  image_dir: ??
  ann_path: ??
  batch_size: 1
  output_image_width: 1000
  output_image_height: 300
  include_masks: True
spatial_aug:
  rotation:
    angle: [0, 10, 30]
  translation:
    translate_x: [0, 100, 200]
    translate_y: [0, 100, 200]
gpu_ids: [0]
num_gpus: 1
