data:
  image_dir: "/datasets/kitti/images"
  ann_path: "/datasets/kitti/labels"
  dataset_type: 'kitti'
  batch_size: 2
  include_masks: False
  output_image_width: 1000
  output_image_height: 300
spatial_aug:
  rotation:
    angle: [0, 10, 30]
gpu_ids: [0]
num_gpus: 1