results_dir: ???
gpu_ids: [0]
batch_size: 4
num_workers: 8
autolabel_type: "grounding_dino"
grounding_dino:
  model:
    backbone: swin_base_384_22k
  dataset: 
    image_dir: ???
    # noun_chunk_path: ???  # If grounding setting
    class_names: ["person", "car"]  # If closed-set detection

  checkpoint: ???
  visualize: True
  iteration_scheduler:
    - conf_threshold: 0.5
      nms_threshold: 0.0
    - conf_threshold: 0.4
      nms_threshold: 0.0
